import type { AnalysisJson } from './jobs'

export const SAMPLE_REPORT_ID = 'sample'
export const SAMPLE_REPORT_ROUTE = '/check/sample-report'
export const SAMPLE_REPORT_CREATED_AT = '2026-02-10T09:30:00.000Z'

export const SAMPLE_ANALYSIS: AnalysisJson = {
  status: 'ok',
  employee: 'Dr Sample',
  pay_date: '15.01.2026',
  pay_period_start: '29.12.2025',
  pay_period_end: '11.01.2026',
  base_rate: 65.4,
  is_overpayment_payslip: false,
  adjustment_total: 758.1,
  older_adjustments_total: 0,
  avac_results: [
    {
      avac_name: 'AVAC Week 1.pdf',
      report: {
        overall_status: 'DISCREPANCIES_FOUND',
        match_count: 1,
        discrepancy_count: 2,
        missing_count: 1,
        unmatched_count: 0,
        check_previous_count: 1,
        check_future_count: 1,
        within_window_issue_count: 0,
        not_yet_paid_count: 0,
        possibly_missed_count: 0,
        earliest_adjustment_date: '30.12.2025',
        latest_adjustment_date: '11.01.2026',
        total_expected: 578.1,
        total_actual: 194.3,
        total_difference: -383.8,
        days: [
          {
            date: '30.12.2025',
            day_of_week: 'Tue',
            day_type: 'weekday',
            status: 'UNDERPAID',
            expected_total: 188.2,
            actual_total: 126.8,
            difference: -61.4,
            items: [
              {
                date: '30.12.2025',
                day_of_week: 'Tue',
                pay_type: 'Overtime_-_1.5',
                status: 'UNDERPAID',
                expected_units: 2.8,
                actual_units: 1.9,
                expected_amount: 188.2,
                actual_amount: 126.8,
                difference: -61.4,
                notes: 'Paid units are lower than expected.',
              },
            ],
          },
          {
            date: '02.01.2026',
            day_of_week: 'Fri',
            day_type: 'weekday',
            status: 'OK',
            expected_total: 67.5,
            actual_total: 67.5,
            difference: 0,
            items: [
              {
                date: '02.01.2026',
                day_of_week: 'Fri',
                pay_type: 'Overtime_-_1.5',
                status: 'MATCH',
                expected_units: 1,
                actual_units: 1,
                expected_amount: 67.5,
                actual_amount: 67.5,
                difference: 0,
                notes: '',
              },
            ],
          },
          {
            date: '06.01.2026',
            day_of_week: 'Tue',
            day_type: 'weekday',
            status: 'CHECK_PREVIOUS',
            expected_total: 110,
            actual_total: 0,
            difference: -110,
            items: [
              {
                date: '06.01.2026',
                day_of_week: 'Tue',
                pay_type: 'Recall_-_T2.0',
                status: 'CHECK_PREVIOUS',
                expected_units: 2,
                actual_units: 0,
                expected_amount: 110,
                actual_amount: 0,
                difference: -110,
                notes: 'Likely included on previous payslip.',
              },
            ],
          },
          {
            date: '09.01.2026',
            day_of_week: 'Fri',
            day_type: 'weekday',
            status: 'MISSING',
            expected_total: 92.4,
            actual_total: 0,
            difference: -92.4,
            items: [
              {
                date: '09.01.2026',
                day_of_week: 'Fri',
                pay_type: 'Overtime_-_2.0',
                status: 'MISSING',
                expected_units: 1.4,
                actual_units: 0,
                expected_amount: 92.4,
                actual_amount: 0,
                difference: -92.4,
                notes: 'No matching payslip entry found.',
              },
            ],
          },
          {
            date: '11.01.2026',
            day_of_week: 'Sun',
            day_type: 'sunday',
            status: 'CHECK_FUTURE',
            expected_total: 120,
            actual_total: 0,
            difference: -120,
            items: [
              {
                date: '11.01.2026',
                day_of_week: 'Sun',
                pay_type: 'Shift-Sunday_Loading-100%',
                status: 'CHECK_FUTURE',
                expected_units: 4,
                actual_units: 0,
                expected_amount: 120,
                actual_amount: 0,
                difference: -120,
                notes: 'Expected on a future payslip.',
              },
            ],
          },
        ],
        actionable_items: [
          {
            date: '30.12.2025',
            day_of_week: 'Tue',
            pay_type: 'Overtime_-_1.5',
            status: 'UNDERPAID',
            expected_units: 2.8,
            actual_units: 1.9,
            expected_amount: 188.2,
            actual_amount: 126.8,
            difference: -61.4,
            notes: 'Paid units are lower than expected.',
          },
          {
            date: '09.01.2026',
            day_of_week: 'Fri',
            pay_type: 'Overtime_-_2.0',
            status: 'MISSING',
            expected_units: 1.4,
            actual_units: 0,
            expected_amount: 92.4,
            actual_amount: 0,
            difference: -92.4,
            notes: 'No matching payslip entry found.',
          },
          {
            date: '06.01.2026',
            day_of_week: 'Tue',
            pay_type: 'Recall_-_T2.0',
            status: 'CHECK_PREVIOUS',
            expected_units: 2,
            actual_units: 0,
            expected_amount: 110,
            actual_amount: 0,
            difference: -110,
            notes: 'Likely included on previous payslip.',
          },
          {
            date: '11.01.2026',
            day_of_week: 'Sun',
            pay_type: 'Shift-Sunday_Loading-100%',
            status: 'CHECK_FUTURE',
            expected_units: 4,
            actual_units: 0,
            expected_amount: 120,
            actual_amount: 0,
            difference: -120,
            notes: 'Expected on a future payslip.',
          },
        ],
        older_adjustments: [],
        older_adjustments_total: 0,
        unmatched_payslip_entries: [],
      },
    },
    {
      avac_name: 'AVAC Week 2.pdf',
      report: {
        overall_status: 'ALL_MATCH',
        match_count: 2,
        discrepancy_count: 0,
        missing_count: 0,
        unmatched_count: 0,
        check_previous_count: 0,
        check_future_count: 0,
        within_window_issue_count: 0,
        not_yet_paid_count: 0,
        possibly_missed_count: 0,
        earliest_adjustment_date: '03.01.2026',
        latest_adjustment_date: '05.01.2026',
        total_expected: 180,
        total_actual: 180,
        total_difference: 0,
        days: [
          {
            date: '03.01.2026',
            day_of_week: 'Sat',
            day_type: 'saturday',
            status: 'OK',
            expected_total: 88,
            actual_total: 88,
            difference: 0,
            items: [
              {
                date: '03.01.2026',
                day_of_week: 'Sat',
                pay_type: 'Shift_-_Sat_Loading_-_50%',
                status: 'MATCH',
                expected_units: 4,
                actual_units: 4,
                expected_amount: 88,
                actual_amount: 88,
                difference: 0,
                notes: '',
              },
            ],
          },
          {
            date: '05.01.2026',
            day_of_week: 'Mon',
            day_type: 'weekday',
            status: 'OK',
            expected_total: 92,
            actual_total: 92,
            difference: 0,
            items: [
              {
                date: '05.01.2026',
                day_of_week: 'Mon',
                pay_type: 'Overtime_-_1.5',
                status: 'MATCH',
                expected_units: 1.4,
                actual_units: 1.4,
                expected_amount: 92,
                actual_amount: 92,
                difference: 0,
                notes: '',
              },
            ],
          },
        ],
        actionable_items: [],
        older_adjustments: [],
        older_adjustments_total: 0,
        unmatched_payslip_entries: [],
      },
    },
  ],
}

export function isSampleReportId(id: string): boolean {
  return id === SAMPLE_REPORT_ID
}
